### ISSUE TITLE
Use `focus-within` utility

### ISSUE THREAD

**Issue by loicknuchel** [matheus23/elm-default-tailwind-modules#1]
Hi @matheus23,

First thanks a lot for this package, it helps me a lot building https://azimutt.app and I use it a lot :heart: 

I just have a question, is there a way to use `focus-within` prefix with it?
(cf https://tailwindcss.com/docs/hover-focus-and-other-states#focus-within)

I tried several tricks but without success...
(you can have a look at https://github.com/azimuttapp/azimutt/pull/57/commits/d923f49f02d4b2c95a9296b261dda714eae8f172#diff-90645b4ce1dcb3cdede38fa9621d9786ddf543ade17935d44341f3b7df616e8eR38)

Any idea of what I can do to have it work?

Thanks a lot.
Loïc

**Comment by matheus23** [comment]
Hi @loicknuchel.

Thanks for the kind words.

The magic of elm-tailwind-modules is that you can just use elm-css for these kinds of things and don't need the prefixed variants from tailwindcss anymore. For your issue you can use [`pseudoElement`](https://package.elm-lang.org/packages/rtfeldman/elm-css/latest/Css#pseudoClass):

```elm
import Css
import Tailwind.Utilities as Tw

elem = div [ css [ Css.pseudoElement "focus-within" [ Tw.xyz ] ] [ text "Hi!" ]
```

**Comment by loicknuchel** [comment]
Hi!

Thanks for your quick response.

I didn't know about `pseudoElement` and `pseudoClass` (still an Elm beginner and even more regarding elm-css ^^).

I could make it work and build my own `focusWithin`:

```elm
import Css exposing (Style, pseudoClass)

focusWithin : List Style -> Style
focusWithin =
    pseudoClass "focus-within"
```
(cf https://github.com/azimuttapp/azimutt/blob/e9dcd80776a518d73ddb2135c2e057299905200b/src/Libs/Tailwind/Utilities.elm)

So I can do:

```elm
div [ css [ focusWithin [ text_gray_600 ] ] ] []
```

And it works well :tada: 
Thanks a lot, I couldn't make it without you ;)

What about adding this (and others similar) to your lib?

I'm closing the issue as it's solved.

**Comment by matheus23** [comment]
> What about adding this (and others similar) to your lib?

I think this is an issue for elm-css, as [it already includes similar definitions](https://github.com/rtfeldman/elm-css/blob/5bedf75bd8bdb12caec8eacd9a316e4cdafc8e35/src/Css.elm#L7359-L7364).

If I decide to add it to this library, then why only include `focusWithin`? What about other utilities? And what if at some point elm-css adds support for `focusWithin`? Should I remove that definition from elm-tailwind-modules?
So I'd rather not add it, as I think it doesn't belong into elm-tailwind-modules, even if it makes the lives of some developers easier :)

**Comment by loicknuchel** [comment]
Indeed I still have a lot to learn as I thought `focus-within` was specific to tailwind, but [it's not](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within) ^^
So you're totally right, it should be added more to elm-css than elm-tailwind-modules.

Thanks again for you lib and your time answering my questions.
Cheers.
