### ISSUE TITLE
Use `group-hover` utility

### ISSUE THREAD

**Issue by loicknuchel** [matheus23/elm-default-tailwind-modules#3]
Hi! Again ;)

Still heavily working with Tailwind to revamp [Azimutt](https://github.com/azimuttapp/azimutt/pull/57) (:scream:) and this time I'm blocking with [group-hover](https://tailwindcss.com/docs/hover-focus-and-other-states#group-hover).

It seems to be a specific tailwind class and I couldn't figure out how to use it.

Do you have an idea?
Thanks!

**Comment by matheus23** [comment]
Yes, unfortunately the `.group-hover` trick that tailwind uses can't be implemented with elm-css (which this library is using), so you'll need to do something to work around that.

Here's a similar discussion from the elm-tailwind-modules issue: https://github.com/matheus23/elm-tailwind-modules/issues/8#issuecomment-891286749

**Comment by loicknuchel** [comment]
Thanks for the reference, interesting discussions.
For now, I think I will adapt my design so I don't need it, even if not ideal.

Also, discovered https://elmcsspatterns.io in the comments, quite nice :D
